### PR TITLE
Re-add the require node

### LINKED ISSUE #200: Job Requirements doesn't work
Hi all.
When i add a new job i use this and i edit with the level , name, sets and the job requirements but when i use in game i can't switch on the second job and i saw this:"minerrank2 does not exist"
This is the jobs.conf and i have added the same sets as miner but with a new amount of a block:
```
miner {
    require {
        job=""
        level=0
        permission="totaleconomy.job.miner"
    }
    salary=20
    sets=[
        ores
    ]
}
minerrank2 {
    require {
        job="miner"
        level=25
        permission="totaleconomy.job.minerrank2"
    }
    salary=30
    sets=[
        ores2
    ]
}
```
If someone knows something about this can he help me, please.
Have a good day all.

### PR DESCRIPTION
**Pull request by MarkL4YG**
Small PR to re-add the ``require`` node to the job logic.  

I don't know when that got lost though.  

* Fixes #200

### CODE REVIEW

File: src/main/java/com/erigitic/jobs/TEJob.java [hunk 1]
```diff
@@ -48,6 +48,18 @@ public TEJob(ConfigurationNode node) {
...
+            ConfigurationNode req = node.getNode("require");
+
+            if (!req.isVirtual()) {
+                String job = req.getNode("job").getString(null);
+                int level = req.getNode("level").getInt(0);
+                String permission = req.getNode("permission").getString(null);
+
+                if (job != null && (job.trim().isEmpty())) {
+                    job = null;
+                }
```
Comment (Erigitic) [inline src/main/java/com/erigitic/jobs/TEJob.java]: Add new line after `}`
