### PR TITLE
Fix keys being registered at the wrong time.

### LINKED ISSUE #262: Issue with the shop system
First of: there is already a issue with this content #260 
so if you dont need this, you could close this issue 

Sponge Version:  spongeforge-1.12.2-2611-7.1.0-BETA-2990
Forge Version:  forge-1.12.2-14.23.2.2611-universal
Total Economy Version:  TotalEconomy-1.8.0

### Description of issue

I dont know what the issue directly is.
I'm the admin of a server and i wanted to test the shops. So i create one, set some items, buy them and then delete the shop.

Now every time i want to join the server, the server crashs.
crash report below.

how to fix this?
how could i join without crashs?
is there a easy way? maybe delete something in a config file?
### Console errors
[crash-2018-04-22_16.11.14-server.txt](https://github.com/Erigitic/TotalEconomy/files/1935826/crash-2018-04-22_16.11.14-server.txt)

### Related Configuration Files
Create a Gist (https://gist.github.com/) for each configuration file related to this issue

### PR DESCRIPTION
**Pull request by dualspiral**
This prevents class not found errors with Nucleus.

From a previous issue on another plugin:

> Register your keys during pre-init by calling something from the class so that the static members are constructed at that time. The class is only loaded when someone calls for a key, which turns out to be me off the main thread, constructing the keys then. Because I’m only getting users, my async operation should be safe.

I plan to make some changes to Nucleus to try to mitigate this if I can work out a performant way to do it, but you should be in control of when your keys are registered, because you're running the risk of your keys possibly being registered under the wrong plugin anyway, depending on implementation of the Sponge server (I'm not sure if you are added to the cause stack when your data is constructed).

Fixes #262

### CODE REVIEW

**Comment by Erigitic** [comment]
Should this be done for the other two keys as well?

**Comment by dualspiral** [comment]
No, you just need the class to be loaded, which is what that line does.

**Comment by Erigitic** [comment]
Alrighty! Thanks for this. I'll get this merged in a few days.

**Comment by dualspiral** [comment]
It's not related. However, that shouldn't happen in stable-7 as the change that would cause that is only in API 8 (bleeding). Just check to see what version of SV you're running - make sure you're not targetting API 8.

**Comment by MarkL4YG** [comment]
I cloned the SV repository and I'm on ``stable-7`` though.
```
On branch stable-7
Your branch is up-to-date with 'origin/stable-7'.
```

File: src/main/java/com/erigitic/main/TotalEconomy.java [hunk 1]
```diff
@@ -280,6 +280,11 @@ private void createAndRegisterData() {
                 .manipulatorId("playershopinfo")
                 .dataName("playershopinfo")
                 .buildAndRegister(pluginContainer);
+
+        // Load the ShopKeys class during init to avoid problems with potential
+        // async loading
```
Comment (Erigitic) [inline src/main/java/com/erigitic/main/TotalEconomy.java]: This comment can be on a single line

**Comment by Erigitic** [comment]
Merge in the latest changes from develop when you can.

**Comment by dualspiral** [comment]
It's a one line change that you should be able to merge yourself. Please feel free to make any edits you need when merging.
